global:
  scrape_interval: 10s
  scrape_timeout: 9s
  evaluation_interval: 15s # How often to check the alert rules

rule_files:
  - "/etc/prometheus/alert_rules.yaml"
scrape_configs:
  - job_name: 'sistema'
    static_configs:
      - targets: ['127.0.0.1:9100']

  - job_name: 'cs2_game'
    static_configs:
      - targets: ['127.0.0.1:9137']

  - job_name: 'network_integrity'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets: ['127.0.0.1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 127.0.0.1:9115